services:
  frontend:
    # TODO: Replace with your actual Docker Hub username, e.g., your-username/junwoo-frontend
    build: .
    image: junwoo-frontend:local
    container_name: community_fe
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://be-backend-1:8000
    networks:
      - be_default

networks:
  be_default:
    external: true
