apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-redis
  labels:
    app: community-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-redis
  template:
    metadata:
      labels:
        app: community-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: community-redis
spec:
  type: ClusterIP
  selector:
    app: community-redis
  ports:
  - port: 6379
    targetPort: 6379
