apiVersion: v1
kind: Service
metadata:
  name: community-backend-service
  labels:
    app: community-backend
spec:
  type: ClusterIP
  selector:
    app: community-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
